//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_ACK
    {
        public int Id { get; set; }
        public Nullable<int> Criteria_Id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<System.DateTime> Ack_Date { get; set; }
        public string Filename { get; set; }
        public Nullable<int> Control { get; set; }
        public Nullable<int> ActionCode { get; set; }
        public string Filetype { get; set; }
        public string Status { get; set; }
    }
}
