//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDI_ReportConverterEntities : DbContext
    {
        public EDI_ReportConverterEntities()
            : base("name=EDI_ReportConverterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ReportHeader> ReportHeaders { get; set; }
        public DbSet<ReportMapping> ReportMappings { get; set; }
    }
}
