//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forwarding
    {
        public int Id { get; set; }
        public string To_EmailId { get; set; }
        public string CC_EmailId { get; set; }
        public string From_EmailId { get; set; }
        public string Host { get; set; }
        public string BCC_EmailId { get; set; }
        public string Email_Subject { get; set; }
        public string Email_Body { get; set; }
    }
}
