//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMapping
    {
        public int Id { get; set; }
        public Nullable<int> ReportHeader_Id { get; set; }
        public string SegmentInitiator { get; set; }
        public Nullable<int> SegmentLocation { get; set; }
        public string FieldName { get; set; }
    }
}
