//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportHeader
    {
        public int Id { get; set; }
        public string PartnerName { get; set; }
        public string Country { get; set; }
        public string ReportType { get; set; }
        public string ElementSeparator { get; set; }
        public string NewlineSeparator { get; set; }
    }
}
