//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduler
    {
        public int Id { get; set; }
        public string ReportName { get; set; }
        public Nullable<int> Forwarding_Id { get; set; }
        public string Time { get; set; }
        public Nullable<int> Retry_Interval { get; set; }
        public Nullable<int> Retry_Count { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
